### PR TITLE
Improve command line build

### PR DESCRIPTION
**Pull request by codedemonuk**
This should allow you to setup automated CI with AppVeyor for your project. You should just be able to point AppVeyor at your repository, and it will automatically detect the YML file and be able to set itself up.

### Notable features

- CI configuration file for AppVeyor (to allow you to set up the project just by pointing AppVeyor at Git)
- Improved the GitVersion output for running on a build server
- Resharper InspectCode analysis
- Resharper Duplicate Code analysis

### CODE REVIEW

**Comment by codedemonuk** [comment]
This should allow you to setup automated CI with AppVeyor for your project.  You should just be able to point AppVeyor at your repository, and it will automatically detect the YML file and be able to set itself up.

**Review by DianaIonita — APPROVED** [review]
Oh nice, thank you! This is the first time I'm hearing about AppVeyor. How do you find it compared to other CIs like Circle (I know, it doesn't have Windows agents)?

Also build scripts are starting to look more complicated than the actual app 😄

**Comment by DianaIonita** [comment]
[Success](https://ci.appveyor.com/project/DianaIonita/spotifylyrics)!

**Comment by codedemonuk** [comment]
It’s similar to the other CI tools that are out there - but for this project main advantage of AppVeyor is that it has real windows build agents. 

Travis can build .net apps but uses mono on Linux which is not the same - especially for a desktop app.

**Pull request merged**
